config/routes.rb
Rails.application.routes.draw do

  root "pets#index"
  resources :pets
  resources :payments

  post '/webhooks', to: 'webhooks#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  # serialize :picUrlSq, Array

  validates :name, :race, :breed, :favoriteFood, presence: true
  validate :birthday_cannot_be_in_the_future
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :picUrl, :picUrlSq, format: { with: /\A(http|https):\/\/\S+\z/ }
  validates :description, length: { minimum: 140 }
  validates :fetch, presence: true, allow_blank: true

  def fetching?
    fetch || fetch.nil?
  end

  # Search method for Pet model
  def self.search(query)
    if query.present?
      where("LOWER(name) LIKE LOWER(:query) OR LOWER(description) LIKE LOWER(:query) OR LOWER(favoriteFood) LIKE LOWER(:query) OR LOWER(breed) LIKE LOWER(:query) OR LOWER(race) LIKE LOWER(:query)", query: "%#{query}%")
    else
      all
    end
  end

  before_save :sanitize_fields

  private

  def birthday_cannot_be_in_the_future
    if birthday.present? && birthday > Date.today
      errors.add(:birthday, "cannot be in the future")
    end
  end

  def sanitize_fields
    self.picUrlSq = Sanitize.fragment(picUrlSq, Sanitize::Config::RELAXED)
    self.description = Sanitize.fragment(description, Sanitize::Config::RESTRICTED)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
  end

  def create
    #create stripe customer for payment, update if already created
    customer = Stripe::Customer.create(
      name: current_user.full_name,
      email: current_user.email,
      description: "Customer id: #{current_user.id}",
    )

    session = Stripe::Checkout::Session.create(
      customer: customer,
      payment_method_types: [‘card’],
      line_items: [{
        price: 'price_1NEN2NCXFStL0CViN1JWm9DH', #price api id usually starts with price_ApIiD
        quantity: 1,
      }],
      mode: 'subscription',
      success_url:  payments_success_url,
      cancel_url: payments_cancel_url
     )

      # Send email to the buyer
      PetPurchaseMailer.purchase_confirmation(@pet, current_user.email).deliver_now

     redirect_to session.url
  end

  def success
    #handle successful payments
    redirect_to root_url, notice: "Purchase Successful"
  end

  def cancel
    #handle if the payment is cancelled
    redirect_to root_url, notice: "Purchase Unsuccessful"
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  # def index
  #   @pets = Pet.search(params[:search])
  # end

  def index
    # When the user searches for a pet, the search method in the Pet model is called
    # Pagination is also implemented here
    @pets = Pet.search(params[:search]).page(params[:page]).per(9)

    respond_to do |format|
      format.html # Render the index.html.erb template for HTML requests
      format.json { render json: @pets } # Respond with JSON for JSON requests
    end

  end

  def show
    # When the user clicks on a pet, the show method in the Pet model is called
    @pet = Pet.find(params[:id])

    respond_to do |format|
      format.html # Render the show.html.erb template for HTML requests
      format.json { render json: @pet } # Respond with JSON for JSON requests
    end

  end

  def edit
    # When the user clicks edit on a pet, the edit method in the Pet model is called
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params)
      redirect_to @pet, notice: "Pet was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @pet = Pet.new

    respond_to do |format|
      format.html # Render the new.html.erb template for HTML requests
      format.json { render json: @pet } # Respond with JSON for JSON requests
    end
  end

  # def create
  #   @pet = Pet.new(pet_params)
  #   if @pet.save
  #     redirect_to @pet, notice: "Pet was successfully created."
  #   else
  #     render :new, status: :unprocessable_entity
  #   end
  # end

  def create
    @pet = Pet.new(pet_params)

    # Upload the image to Cloudinary and get the secure_url
    image_url = upload_image(params[:pet][:image])

    # Assign the image_url to the @pet instance
    @pet.picUrlSq = image_url

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: "Pet was successfully created." }
        format.json { render json: @pet, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  def upload_image(image)
    response = Cloudinary::Uploader.upload(image.path)
    response["secure_url"]
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, status: :see_other, alert: "Pet was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :race, :breed, :birthday, :favoriteFood, :picUrl, :price, :picUrlSq, :description, :fetch, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper

  def loveFetch(pet)
    if pet.fetching?
      "I love fetching!"
    else
      "I don't fetch"
    end
  end

  def priceless(pet)
    if pet.price && pet.price > 50
      content_tag(:strong, "Priceless")
    elsif pet.price
      content_tag(:i, "#{number_to_currency(pet.price, precision: 0)}")
    else
      content_tag(:i, "N/A")
    end
  end

end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>Copyright &copy; <%= Time.now.year %> Moose's Pet Store</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag("logo1.png"), root_path %>
    <ul>
      <li><%= link_to "Home", pets_path %></li>
    </ul>
    <div>
      <%= form_tag(pets_path, method: :get) do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search pets" %>
      <%= submit_tag "Search" %>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moose's Pet store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "layouts/header" %>

    <div class="content">
    <%= render "layouts/flash" %>
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>

  </body>
</html>

app/views/payments/new.html.erb
<%= form_tag payments_path do %>
  <label class="amount">
      <span>Amount: $5.00</span>
  </label>



  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Cost of the Pet!"
    data-amount="500"
    data-locale="auto">
  </script>

<% end %>

app/views/pets/_form.html.erb
<%= form_with(model: pet) do |form| %>

  <%= render "shared/errors", object: pet %>

  <%= pet.errors.full_messages.to_sentence %>

  <%= form.label :name %>
  <%= form.text_field :name, autofocus: true %>

  <%= form.label :race %>
  <%= form.text_field :race %>

  <%= form.label :breed %>
  <%= form.text_field :breed %>

  <%= form.label :birthday %>
  <%= form.date_field :birthday %>

  <%= form.label :favoriteFood %>
  <%= form.text_field :favoriteFood %>

  <%= form.label :picUrl %>
  <%= form.text_field :picUrl %>

  <%= form.label :price %>
  <%= form.number_field :price %>

  <%# <%= form.label :picUrlSq %>
  <%# <%= form.text_field :picUrlSq %>

  <% if controller_name == 'pets' && action_name == 'new' %>
    <%= form.label :image %>
    <%= form.file_field :image %>
  <% elsif controller_name == 'pets' && action_name == 'edit' %>
    <%= form.label :picUrlSq %>
    <%= form.text_field :picUrlSq %>
  <% end %>

  <%= form.label :description %>
  <%= form.text_area :description, rows: 5 %>

  <%= form.label :fetch %>
  <%= form.check_box :fetch %>

  <%= form.submit %>

<% end %>

app/views/pets/edit.html.erb
<h1> Editing <%= @pet.name %></h1>

<%= render "form", pet: @pet %>

app/views/pets/index.html.erb
<div class="container">
  <div class="row">
    <% if @pets.any? %>
      <% @pets.each do |pet| %>
        <div class="col-lg-4 col-md-6 col-sm-12">
        <section class='pet'>
          <div class='summary'>
            <h2><%= link_to(pet[:name], pet_path(pet)) %></h2>
            <img class="image" src="<%= pet[:picUrl] %>" alt="<%= pet[:name] %>">
            <p class="breed">Race:<%= pet[:race] %></p>
            <p class="breed">Breed:<%= pet[:breed] %></p>
            <p class="price">Price: <%= priceless(pet) %></p>
            <p class="description"><%= truncate(pet[:description], length:40, separator: ' ') %></p>
            <p><%= loveFetch(pet)%></p>
          </div>
          </section>
        </div>
      <% end %>
    <% else %>
      <div class="col-12">
        <p>Nothing found, try your search again!</p>
        <%= link_to "Home", pets_path %>
      </div>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <%= paginate @pets %>
  </div>
</div>
<section class="admin">
  <%= link_to "Add New Pet", new_pet_path, class: "button" %>
</section>

app/views/pets/new.html.erb
<h1> Create a new Pet</h1>

<%= render "form", pet: @pet %>

app/views/pets/payment.html.erb
<%= form_tag charges_path do %>

  <article>

    <% if flash[:error].present? %>

      <div id=”error_explanation”>

        <p><%= flash[:error] %></p>

      </div>

    <% end %>

    <label class=”amount”>

    <span>Amount: $<%= @order.price %></span>

    </label>

  </article>

  <script src=”https://checkout.stripe.com/checkout.js” class=”stripe-button”

    data-key=”<%= Rails.configuration.stripe[:publishable_key] %>”

    data-description=”A month’s subscription”

    data-amount=”<%= @order.price %>”

    data-locale=”auto”></script>

<% end %>

app/views/pets/show.html.erb
<section class="pet-details">
  <div class="details">
    <div class='summary'>
      <h2><%= @pet.name %></h2>
      <img class="image" src="<%= @pet.picUrl %>" alt="<%= @pet.name %>">
      <p class="breed">Race:<%= @pet.race %></p>
      <p class="breed">Breed:<%= @pet.breed %></p>
      <p class="food">Food:<%= @pet.favoriteFood %></p>
      <p class="price">Price: <%= priceless(@pet) %></p>
      <p class="description"><%= @pet.description %></p>
      <img class="image" src="<%= @pet.picUrlSq %>" alt="<%= @pet.name %>">
      <p>By the way, <%= loveFetch(@pet)%></p>
      <label class="amount">
        <span>Amount: <%= @pet.price %></span>
      </label>
      <script
        src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-description="Pet Costs <%= @pet.price %>"
        data-amount="<%= @pet.price * 100 %>"
        data-locale="auto">
      </script>
    </div>
  </div>
  <section class="admin">
    <%= link_to "Home", pets_path, class: "button"  %>
    <%= link_to "Edit", edit_pet_path(@pet), class: "button" %>
    <%= link_to "Delete", @pet, class: "button",
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
  </section>
</section>

app/views/shared/_errors.html.erb
  <% if object.errors.any? %>
    <section class="errors">
      <h2>
        Oops! Your form could not be saved..
      </h2>
      <h3>
        Please correct the following
        <%= pluralize(object.errors.size, "error") %>:
      </h3>
      <ul>
        <% object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </section>
  <% end %>